CI: Use pre-compiled "cross"
strawlab/iana-time-zone pull request #93
Opened 2022-12-30 10:21 UTC by Kijewski

2022-12-30 11:30 UTC, astraw requested changes
Can you put a comment documenting how you got this relatively complex command to help maintain this?

2022-12-30 17:33 UTC, Kijewski commented
@astraw, ah, yes, of course. I had to read up what the flags mean, too. :)

2023-01-09 20:15 UTC, astraw approved these changes

2023-01-09 20:15 UTC, merged

2023-01-09 20:16 UTC, astraw commented
Great, thanks!